### ISSUE TITLE
protospace挙動確認

### ISSUE THREAD

**Issue by sorakanda** [sorakanda/protospace-38723#1]
https://protospace-38723.onrender.com/

**Comment by motomuun** [comment]
@sorakanda さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**その他**
- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他のユーザーのプロトタイプ編集ページに遷移できてしまいます。出来ないように修正をお願いします。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7
